files: ""
repos:
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--verbose"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    # reference: https://pre-commit.com/hooks.html
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=auto

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      # - id: commitizen-branch
      #   stages: [push]
#    - repos:
#      - hooks:
#          - id: commitizen
#            stages:
#              - commit-msg
#        repo: https://github.com/commitizen-tools/commitizen
#        rev: v2.1.0
