# Generated by Django 5.1.6 on 2025-03-01 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmetadata",
            name="authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=[], size=None
            ),
        ),
        migrations.AlterField(
            model_name="bookmetadata",
            name="bookshelves",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=[], size=None
            ),
        ),
        migrations.AlterField(
            model_name="bookmetadata",
            name="subjects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=[], size=None
            ),
        ),
    ]
