# Generated by Django 5.1.6 on 2025-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_bookanalysis_book_alter_bookmetadata_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmetadata",
            name="title",
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
