# Generated by Django 5.1.6 on 2025-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookmetadata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookanalysis',
            name='analyse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
