# Generated by Django 5.1.6 on 2025-03-05 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookanalysis_analyse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookanalysis',
            name='character_relationships',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='key_characters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='notable_quotes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='sentiment_and_emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='bookanalysis',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
    ]
