# Generated by Django 5.1.6 on 2026-05-16 07:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookanalysis_character_relationships_and_more'),
    ]

    operations = [
        VectorExtension(),
    ]
