# Generated by Django 5.1.6 on 2026-05-19 07:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_init_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('token_count', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_gin_index'), pgvector.django.indexes.HnswIndex(fields=['embedding'], name='embedding_hnsw_index', opclasses=['vector_cosine_ops']), models.Index(fields=['book', 'chunk_index'], name='book_chunk_index_index')],
                'constraints': [models.UniqueConstraint(fields=('book', 'chunk_index'), name='unique_book_chunk_index')],
            },
        ),
    ]
