# Generated by Django 5.1.6 on 2026-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_bookconversation_bookconversationmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchunk',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
