# Generated by Django 5.1.6 on 2026-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_bookchunk_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
